### ISSUE TITLE
Sistema de moderación de articulos?

### ISSUE THREAD

**Issue by manugarri** [Pybonacci/pybonacci.github.io-source#18]
Dado que el sistema va a pasar a ser mas abierto (con cualquiera que sepa como hacer una PR pudiendo proponer contenido), ¿Como vamos a moderar los artículos?.

No me importa nominar a kiko como BDFL, pero deberiamos tener una nota sobre la moderación en la guia de contribucion para que el proceso sea transparente. Además claro que no sé como tiene la carga de trabajo @kikocorreoso .

**Comment by kikocorreoso** [comment]
Cuando lleguen miles de artículos y podamos vivir de AdSense me podré dedicar completamente a Pybonacci. Muahahahahaha

Ahora en serio, para la carga de trabajo que hay en pybonacci (aceptación de un artículo a la semana como muchísimo??) la moderación puede ser simplemente mergear el PR cuando todo esté correcto. Lo puede revisar quien sea (todos los editores) y mergear quién sea (hoy creo que solo @Juanlu001 o @kikocorreoso pero se puede cambiar sin problemas).

Es decir, la revisión puede estar a cargo de 5 personas y con que una diga que adelante luego se mergea (2 personas pero que pueden ser más). No hace falta BDFL 😈

**Comment by Juanlu001** [comment]
El equipo @Pybonacci/editores tiene permisos de escritura.

Propongo que funcionemos así: cuando el artículo tiene dos revisiones positivas, se mergea. Y que lo revise quien quiera, o quien tenga interés en función de su área de conocimiento, o en su defecto @kikocorreoso y yo.

¿Todo el mundo de acuerdo? ¿Documentamos esto en algún sitio?

**Comment by kikocorreoso** [comment]
Se puede documentar y se puede establecer que cualquiera podría ser editor después de x pasos. Algo parecido a conda-forge.

* Después de haber contribuido con tres artículos?
* Después de hacer commiteado cosas relevantes a pybonacciblog en un par de ocasiones, al menos?
* Por invitación de otro editor?
* ...

**Comment by manugarri** [comment]
Me parece bien. :+1 asi solo necesitamos que dos personas dediquen unos minutos y a la vez garantizamos que no haya bias de una sola persona.

Lo añado al CONTRIBUTING.md

**Comment by manugarri** [comment]
@kikocorreoso @Juanlu001  que pensais respecto al proceso para invitar a nuevos editores?

**Comment by Juanlu001** [comment]
¡Escribir 3 artículos me parece bien! Y al tercero que ya gane acceso de escritura (equipo @Pybonacci/editores).

**Comment by manugarri** [comment]
Excellent, lo añado al CONTRIBUTING.md entonces. Siempre podemos cambiarlo en el futuro.
