### ISSUE TITLE
Add author box

### ISSUE THREAD

**Issue by Juanlu001** [Pybonacci/pybonacci.github.io-source#2]
This might require some work.

**Comment by manugarri** [comment]
@Juanlu001 puedo echarle un ojo, por Author box nos referimos a crear una página sobre cada autor? O que en cada artículo abajo aparezca información contextual sobre el autor.

**Comment by Juanlu001** [comment]
Yo había pensado en cada artículo, pero puede ser complicado. La idea de tener un enlace a una página por autor también está bien!

**Comment by manugarri** [comment]
Esto es más peliagudo de lo que parece. Tengo varias opciones de momento.

### Opcion 1 (facil) - Link en el footer de cada articulo a pagina de autor.

Esto es sencillo, basicamente hay que hacer:

1. Crear un md por autor en `content/pages/author`. Por ejemplo, el archivo manuel-garrido.md tendria este aspecto:

  ```---
title: Manuel Garrido
slug: manuel-garrido
Template: about_author
description: Manuel es genial
avatar: https://media.licdn.com/mpr/mpr/shrinknp_400_400/AAEAAQAAAAAAAAJ_AAAAJDQ1MzNjMDFkLWI1ZmQtNGFjYy1iYWY1LWMxNjMxNDg4M2U3OA.jpg
```

2. Crear un template `about_author.html` esto no es obligatorio, pero ayuda a separar los bloques, un ejemplo patatero de este template seria:
```
avatar: https://media.licdn.com/mpr/mpr/shrinknp_400_400/AAEAAQAAAAAAAAJ_AAAAJDQ1MzNjMDFkLWI1ZmQtNGFjYy1iYWY1LWMxNjMxNDg4M2U3OA.jpg
```

3. Referenciar en el template `article.html` donde se quiera el link, una forma facil (un poco hacky eso si) de hacer esto es por ejemplo:

```
{% for author in article.authors %}
    <a href="/pages/{{ author|replace(" ","-")|lower }}.html">Informacion sobre {{ author }}</a>
{% endfor %}
```

### Opción 2: Footer con descripcion dinamica del autor.

He estado mirando esto, y la forma que se recomienda en [este issue](https://github.com/getpelican/pelican/issues/1735) es usando el plugin Category Metadata. Basicamente se moveria todo el content a subcarpetas, una por autor, y en cada subcarpeta se pondria un `index.md` con informacion sobre el autor (imagen, bio, lo que se quiera) que se podria referenciar directamente en `article.html`.

No obstante, esta opción plantea dos problemas:
  - El plugin Category Metadata [no funciona en la última versión de Pelican](https://github.com/getpelican/pelican-plugins/issues/855), y además parece descontinuado. 
  - No me queda muy claro como funcionaría esto con los jupyter notebooks (cada md creado por los jupyter tendria que ir a la carpeta del respectivo autor).

Se me ocurren dos alternativas mas sencillas:
 - Simplemente crear un template por autor en `theme/templates/author/` con el html creado para el autor e incluirlo en `article.html` como  

```
    {% for author in article.authors %}
      {% include author.url  ignore missing %}
    {% endfor %}
```

  - Añadir el metadata en cada articulo *(article_author_bio, article_author_img)...)* y referenciar dicha metadata en la plantilla de articulo. Esta opcion me parece demasiado repetir codigo.

Que pensais @Pybonacci/editores ?

**Comment by Juanlu001** [comment]
Tu opción 1 y la primera alternativa simple son las que más me gustan, lo otro es complicado o repetitivo. Por lo que he entendido la primera alternativa simple permite tener la bio en el mismo artículo y además en pocos pasos, ¿tiramos por ahí?

**Comment by manugarri** [comment]
@Juanlu001 estoy de acuerdo, me pongo con la alternativa 1.

**Comment by manugarri** [comment]
cierro
