### ISSUE TITLE
Explicitly state license

### ISSUE THREAD

**Issue by Juanlu001** [Pybonacci/pybonacci.github.io-source#6]
In Pybonacci we used CC BY-SA 3.0 Unported. There's no trace of license in the current version of the blog but I would like to revert that. If we are to use the same license as before, we should probably go for CC BY-SA 4.0 International:

https://creativecommons.org/licenses/by-sa/4.0/deed.es_ES

But [CC licenses should not be used for code](https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software) so perhaps we can put a simpler, more permissive license for code snippets and cells, such as MIT.

Does everybody agree?

**Comment by Juanlu001** [comment]
@Pybonacci/editores 

Si alguien no está de acuerdo en usar CC BY-SA 4.0 Internacional para el contenido + MIT para el código, que hable ahora o calle para siempre.

**Comment by kikocorreoso** [comment]
👍

**Comment by manugarri** [comment]
:+1:

**Comment by manugarri** [comment]
Donde iria la licencia @Juanlu001 ? La puedo meter en una plantilla.

**Comment by Juanlu001** [comment]
En un footer la pondría yo!

**Comment by manugarri** [comment]
https://github.com/Pybonacci/pybonacci.github.io-source/pull/26 Que os parece @Pybonacci/editores

**Comment by Juanlu001** [comment]
Cerrado en #27 por @manugarri
